from .blockswap import NODE_CLASS_MAPPINGS as _WAN_NODES, NODE_DISPLAY_NAME_MAPPINGS as _WAN_NAMES
from .blockswap_ltx import NODE_CLASS_MAPPINGS as _LTX_NODES, NODE_DISPLAY_NAME_MAPPINGS as _LTX_NAMES
from .blockswap_krea2 import NODE_CLASS_MAPPINGS as _K2_NODES, NODE_DISPLAY_NAME_MAPPINGS as _K2_NAMES

NODE_CLASS_MAPPINGS = {**_WAN_NODES, **_LTX_NODES, **_K2_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**_WAN_NAMES, **_LTX_NAMES, **_K2_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
